import java.io.File
import java.nio.file.Files

/** Generates `textmaps.icons.BuiltinIcons` (the shared object backing every built-in, no-`import`-needed
 *  room feature glyph — furnishing icons and Stairs/SpiralStairs/Ladder movement glyphs alike) from the
 *  standalone `.svg` files under `doc/icons/builtin/`. Those files are the *only* place this artwork is
 *  defined; nothing here or in `BuiltinIcons.scala` itself hand-duplicates a glyph's markup — this object
 *  just extracts it. Wired up as a `Compile / sourceGenerators` task in `build.sbt` for the `core`
 *  cross-project, so `BuiltinIcons.scala` is produced fresh into each platform's managed-source directory
 *  on every compile rather than being checked into git. */
object BuiltinIconsGen {
  private val ViewBoxRe = """viewBox="([^"]*)"""".r
  private val PathDRe   = """<path[^>]*\sd="([^"]*)"""".r
  private val SvgInnerRe = """(?s)<svg[^>]*>(.*)</svg>""".r

  // The two glyph "shapes" this project currently has, distinguished by their own viewBox rather than a
  // hardcoded filename list, so a new .svg dropped into doc/icons/builtin/ following either convention is
  // picked up automatically: a furnishing icon (single <path d="...">, Iconify's own 512x512 grid) becomes
  // a `paths` entry; a movement glyph (arbitrary hand-drawn markup, this project's own 30x30 feature grid)
  // becomes a `movementGlyphs` entry.
  private val FurnishingViewBox = "0 0 512 512"
  private val MovementViewBox   = "0 0 30 30"

  private def escape(s: String): String =
    s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")

  /** Strips only leading/trailing newline characters, not indentation — the inner markup's own leading
   *  `  ` (two-space) indent on its first line is part of what `defs()` expects to interpolate as-is. */
  private def stripNewlines(s: String): String = {
    var start = 0
    var end   = s.length
    while (start < end && s(start) == '\n') start += 1
    while (end > start && s(end - 1) == '\n') end -= 1
    s.substring(start, end)
  }

  def generate(svgDir: File, outDir: File): Seq[File] = {
    val files = Option(svgDir.listFiles((_, name) => name.endsWith(".svg")))
      .getOrElse(Array.empty[File])
      .sortBy(_.getName)

    val furnishing = scala.collection.mutable.ListBuffer.empty[(String, String)]
    val movement   = scala.collection.mutable.ListBuffer.empty[(String, String)]

    files.foreach { f =>
      val name    = f.getName.stripSuffix(".svg")
      val content = new String(Files.readAllBytes(f.toPath), "UTF-8")
      val viewBox = ViewBoxRe.findFirstMatchIn(content).map(_.group(1)).getOrElse("")
      viewBox match {
        case FurnishingViewBox =>
          val d = PathDRe.findFirstMatchIn(content).map(_.group(1))
            .getOrElse(sys.error(s"BuiltinIconsGen: no <path d=...> found in $f"))
          furnishing += (name -> d)
        case MovementViewBox =>
          val inner = SvgInnerRe.findFirstMatchIn(content).map(m => stripNewlines(m.group(1)))
            .getOrElse(sys.error(s"BuiltinIconsGen: could not extract inner markup from $f"))
          movement += (name -> inner)
        case other =>
          sys.error(s"BuiltinIconsGen: unexpected viewBox '$other' in $f — expected '$FurnishingViewBox' " +
            s"(furnishing icon) or '$MovementViewBox' (movement glyph)")
      }
    }

    val sb = new StringBuilder
    sb.append("package textmaps.icons\n\n")
    sb.append("// GENERATED by project/BuiltinIconsGen.scala from doc/icons/builtin/*.svg — do not edit by\n")
    sb.append("// hand, edit the .svg files instead and recompile. See doc/icons/builtin/SOURCES.md.\n")
    sb.append("object BuiltinIcons {\n\n")
    sb.append("  // Sentinel RoomFeature.Icon.iconSet value used for the furnishing icons below — routes\n")
    sb.append("  // rendering straight to the builtin-<name> <symbol> in defs() instead of through IconFetcher.\n")
    sb.append("""  val iconSetName: String = "builtin"""" + "\n\n")
    sb.append(s"""  val viewBox: String = "$FurnishingViewBox"""" + "\n\n")
    sb.append("  // Furnishing icons' `d` path attribute, keyed by bare icon name.\n")
    sb.append("  val paths: Map[String, String] = Map(\n")
    furnishing.sortBy(_._1).foreach { case (n, d) =>
      sb.append(s"""    "$n" -> "${escape(d)}",\n""")
    }
    sb.append("  )\n\n")
    sb.append("  // Movement glyphs (Stairs/SpiralStairs/Ladder) inner <symbol> markup, keyed by symbol\n")
    sb.append(s"""  // suffix; all share viewBox "$MovementViewBox".\n""")
    sb.append("  val movementGlyphs: Map[String, String] = Map(\n")
    movement.sortBy(_._1).foreach { case (n, inner) =>
      sb.append(s"""    "$n" -> "${escape(inner)}",\n""")
    }
    sb.append("  )\n")
    sb.append("}\n")

    val outFile = new File(new File(new File(outDir, "textmaps"), "icons"), "BuiltinIcons.scala")
    outFile.getParentFile.mkdirs()
    Files.write(outFile.toPath, sb.toString.getBytes("UTF-8"))
    Seq(outFile)
  }
}
